#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+TITLE: Thesis proposal
#+AUTHOR: Nicola Zanardi
#+OPTIONS: toc:nil

* Introduction
Internal combustion engines are still nowadays the most widely adopted powertrain for on-road vehicles. However, due to inefficiencies in the energy conversion process, around 60-70% of the fuel energy is wasted in form of heat.
An energy and exergy analysis performed on traditional ICEs shows that approximately 40% of the fuel energy leaves the engine in the hot exhaust and another 30% is lost as heat. The largest losses are due to combustion irreversibilities and heat loss to the coolant, through the exhaust, and by direct convection and radiation to the environment. catafrattoo!!!!

The best options for achieving significant improvements in efficiency appears to be recovery of waste heat from the exhaust gases and/or other high energy streams by means of bottoming cycle, intra-cycle recovery, turbo-compounding or thermo-electric technologies.

Regardless of how efficient the engine is, there will still be a significant fraction of the fuel energy that is rejected in the exhaust and coolant streams. Unfortunately, much of the heat transfer either occurs at relatively low temperatures resulting in large entropy generation, is transferred to low-exergy flow streams, or is radiated or convected directly to the environment.

* Thesis proposal
My thesis will be focusing on comparing three different technologies that are aimed at recovery the waste heat produced by the ICE. They are two different configurations of Organic Rankine bottoming cycle bounded to traditional gasoline Otto-cycle engine, and an split-cycle engine with isothermal compression and integrated waste heat recovery.

** Otto-engine with Organic Rankine bottoming cycle
The first system to be analyzed is the already well known pairing of a traditional Otto-cycle gasoline engine with a bottoming Rakine cycle. This system has already been studied and tested extensively since the '70s, and there are also commercial products, mainly heavy-duty, that adopt it.

This powerplant will constitute the "baseline" scenario for the comparison, due to the forementioned diffusion and universal acceptance as a valid waste heat recovery method.

*** Modeling methodology
The powertrain model will take as input a velocity profile (NEDC, WLTC, or any other driving cycle) for which measured torque and angular speed data at the wheel is available. Then a transmission will be implemented, in order to calculate torque and angular speed at the engine. Furthermore, via the modeling of the engine maps it will be possible to calculate the mass flow rate, the temperature and the heat flux of both the exhaust gases and of the coolant.

Once the waste heat data will be available, then the bottoming cycle model will be implemented. Taking as input the output of the first model, the recovered energy and produced power will be calculated, and then the impact of the global efficiency of the engine.

The powertrain model will be assembled starting from already existing projects developed by OSU students in the previous years, and then adapted for the particular case in study. In particular, the road testing data is coming from a 3.6L V6 gasoline equipped Chrysler minivan, and the engine maps and transmission models have been developed accordingly.

*** Assumptions
As a waste heat source, only the heat coming from the exhaust gases will be considered, neglecting the heat contained in the coolant. The reasons behind this decisions are: increased recovery complexity, lower exergetic content and the fact that is a more unusual configuration with respect to the one with only exhausts recovery. Being this the baseline scenario, it has been decided to stick to the most common configuration.

*** Expected results
Being this the baseline case, the results expected should be coherent with the majority of the studies that can be found in literature, that is an expected increase in the global engine efficiency around 6 - 10 %.

** Otto-engine with evaporative cooling Organic Rankine bottoming cycle
The same system as the previous case will be considered, but modified as to remove the heat exchanger between the heat source and the cycle working fluid. This way the ORC working fluid will replace the engine coolant, increasing the amount of energy recovered and reducing the heat and the number of components of the system. As a downside, the control system will become more complex, because it will be necessary to control the refrigerant mass flow rate in order to guarantee the required cooling for the engine at all the operating points.

*** Modeling methodology
The same overall model as the previous case will be used, but it will be modified accordingly to the new cycle configuration. Variable flow rate pumps for the cooling working fluid will be implemented and a control system for assuring the correct cooling of the engine will be introduced.

*** Assumptions
The fluid entering the engine will be assumed as saturated liquid, while the eventual superheating will happen in a heat exchanger using the heat of the exhaust gases

*** Expected results
It's expected an increase in efficiency with respect to the baseline case, due to an increased heat exchange coefficient and better matching of the system with the engine characteristics. More heat is expected to be recovered, with consequent increase of the overall produced power.

** Split-cycle configuration with waste heat recovery
A different engine configuration will be considered in this case. The idea is to compare a bottoming cycle with a different and theoretically more efficient engine design, especially suited to be used in hybrid cars and plug-in vehicles.

*** Modeling methodology
A new model will be written for this engine, with methodologies not yet discussed. 

*** Assumptions
The model will not be a dynamic one, because of the limited time available. It will be optimized for a couple of operating points, representing the use as a range extender for a plug-in hybrid vehicle.
